### ISSUE TITLE
[트리] 폴더명 수정 시 하위 목록이 삭제되는 오류

### ISSUE THREAD

**Issue by HAN-SEOHYUN** [woogieReal/MDGround3#57]
# AS-IS
<li>폴더명 수정 시 하위 폴더 및 파일이 모두 삭제되는 오류</li>

# TO-BE
<li>폴더 명 수정을 해도 하위 폴더 및 파일이 삭제되지 않는다.</li>

**Comment by woogieReal** [comment]
확인해서 수정하겠습니다.
감사합니다~
